- id: '1588533648578'
  alias: '[Alarme] Porte entrée ouverte'
  description: ''
  trigger:
  - device_id: cb834a7d240848d8a22d634f370ddc08
    domain: binary_sensor
    entity_id: binary_sensor.porte_entree_contact
    platform: device
    type: opened
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.alarme
      state: armed_away
    - condition: state
      entity_id: alarm_control_panel.alarme
      state: armed_night
  action:
  - data:
      message: Porte entrée ouverte
    service: notify.telegram
  - data:
      camera_name: sejour
    service: shell_command.send_camera_snapshots
  mode: single
- id: '1588553279361'
  alias: '[Alarme] Porte balcon ouverte'
  description: ''
  trigger:
  - device_id: 7ba2a5d9bee8499180cf9abe0161e8c1
    domain: binary_sensor
    entity_id: binary_sensor.porte_balcon_contact
    platform: device
    type: opened
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.alarme
      state: armed_away
    - condition: state
      entity_id: alarm_control_panel.alarme
      state: armed_night
  action:
  - data:
      message: Porte balcon ouverte
    service: notify.telegram
  - data:
      camera_name: balcon
    service: shell_command.send_camera_snapshots
  mode: single
- id: '1588612500729'
  alias: '[Lumière] Porte entrée ouverte soir'
  description: ''
  trigger:
  - device_id: cb834a7d240848d8a22d634f370ddc08
    domain: binary_sensor
    entity_id: binary_sensor.porte_entree_contact
    platform: device
    type: opened
  condition:
  - condition: and
    conditions:
    - after: '16:00'
      before: 05:00
      condition: time
    - condition: state
      entity_id: input_boolean.occupancy
      state: 'off'
  action:
  - brightness_pct: 100
    device_id: 486d6ad978584ce39674ee4760664c91
    domain: light
    entity_id: light.lampadaire_ikea
    type: turn_on
  - brightness_pct: 100
    device_id: 07fe70d7a5a74521b01a91e46797885b
    domain: light
    entity_id: light.lumiere_salon
    type: turn_on
  mode: single
- id: '1588894249532'
  alias: '[Scan présence] Porte entrée fermé'
  description: ''
  trigger:
  - device_id: cb834a7d240848d8a22d634f370ddc08
    domain: binary_sensor
    entity_id: binary_sensor.porte_entree_contact
    platform: device
    type: not_opened
  condition:
  - condition: state
    entity_id: input_boolean.occupancy
    state: 'on'
  action:
  - delay: '10'
  - data:
      topic: monitor/scan/depart
    service: mqtt.publish
- id: '1588894714461'
  alias: '[Scan présence] Porte entrée ouverte'
  description: ''
  trigger:
  - device_id: cb834a7d240848d8a22d634f370ddc08
    domain: binary_sensor
    entity_id: binary_sensor.porte_entree_contact
    platform: device
    type: opened
  condition:
  - condition: state
    entity_id: input_boolean.occupancy
    state: 'off'
  action:
  - data:
      topic: monitor/scan/arrive
    service: mqtt.publish
- id: 0bbfa6dff2da4aa4a5745dfe5391e234
  alias: '[Set] Occupancy on'
  trigger:
  - above: '10'
    entity_id: sensor.home_occupancy_confidence
    platform: numeric_state
  action:
  - data:
      entity_id: input_boolean.occupancy
    service: input_boolean.turn_on
  - data: {}
    entity_id: alarm_control_panel.alarme
    service: alarm_control_panel.alarm_disarm
- id: 871af6931a384acdbd14983237d19dcf
  alias: '[Set] Occupancy off'
  trigger:
  - below: '10'
    entity_id: sensor.home_occupancy_confidence
    platform: numeric_state
  condition:
  - condition: state
    entity_id: input_boolean.occupancy
    state: 'on'
  action:
  - data:
      entity_id: input_boolean.occupancy
    service: input_boolean.turn_off
- id: '1588902472098'
  alias: Initialisation
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      topic: monitor/scan/restart
    service: mqtt.publish
  - data:
      topic: fujiac/reset/set
    service: mqtt.publish
- id: '1589722828341'
  alias: '[Notification] Sortir poubelles'
  description: ''
  trigger:
  - at: '20:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - tue
  action:
  - data:
      message: N'oubliez pas de sortir les poubelles avant demain matin 8h00
    service: notify.telegram
  - data:
      message: N'oubliez pas de sortir les poubelles avant demain matin 8h00
    service: persistent_notification.create
- id: '1590284669925'
  alias: '[Notification] Alarme activée (absent)'
  description: ''
  trigger:
  - entity_id: alarm_control_panel.alarme
    platform: state
    to: armed_away
  condition: []
  action:
  - data:
      message: Alarme activé (Mode absent)
    service: notify.telegram
- id: '1590285643911'
  alias: '[Notification] Alarme activée (nuit)'
  description: ''
  trigger:
  - entity_id: alarm_control_panel.alarme
    platform: state
    to: armed_night
  condition: []
  action:
  - data:
      message: Alarme activé (Mode nuit)
    service: notify.telegram
- id: '1590285699676'
  alias: '[Notification] Alarme désactivée'
  description: ''
  trigger:
  - entity_id: alarm_control_panel.alarme
    platform: state
    to: disarmed
  condition: []
  action:
  - data:
      message: Alarme désactivé
    service: notify.telegram
- id: '1590371260631'
  alias: Turn off alarm on occupancy on
  description: ''
  trigger:
  - entity_id: input_boolean.occupancy
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: alarm_control_panel.alarme
    service: alarm_control_panel.alarm_disarm
- id: '1590371502482'
  alias: Enable sensors
  description: ''
  trigger:
  - entity_id: alarm_control_panel.alarme
    platform: state
    to: armed_away
  condition: []
  action:
  - data: {}
    entity_id: switch.camera_sejour_motion_sensor
    service: switch.turn_on
- id: '1590371659035'
  alias: Disable sensors
  description: ''
  trigger:
  - entity_id: alarm_control_panel.alarme
    platform: state
    to: disarmed
  condition: []
  action:
  - data: {}
    entity_id: switch.camera_sejour_motion_sensor
    service: switch.turn_off
  - data: {}
    entity_id: switch.camera_balcon_motion_sensor
    service: switch.turn_off
- id: '1590371910210'
  alias: Turn on alarm on occupancy off
  description: ''
  trigger:
  - entity_id: input_boolean.occupancy
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: alarm_control_panel.alarme
    service: alarm_control_panel.alarm_arm_away
- id: '1594307563684'
  alias: '[Notification] Courrier'
  description: ''
  trigger:
  - device_id: 4bb17fef30eb4ab0ad7bb0c01958c2a3
    domain: binary_sensor
    entity_id: binary_sensor.boite_a_lettre_contact
    platform: device
    type: opened
  condition: []
  action:
  - data:
      message: Vous avez reçu du courrier
    service: notify.telegram
  - data:
      message: Vous avez reçu du courrier
    service: persistent_notification.create
- id: '1594674041380'
  alias: '[Notification] Mouvement camera balcon'
  description: ''
  trigger:
  - entity_id: binary_sensor.ip_camera_balcon_motion
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Mouvement sur le balcon
    service: notify.telegram
  - data:
      camera_name: balcon
    service: shell_command.send_camera_snapshots
- id: '1595197177942'
  alias: '[Notification] Mouvement camera séjour'
  description: ''
  trigger:
  - entity_id: switch.camera_sejour_motion_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Mouvement dans le séjour
    service: notify.telegram
  - data:
      camera_name: sejour
    service: shell_command.send_camera_snapshots
- id: '1595505541002'
  alias: '[Notification] Mouvement camera bureau'
  description: ''
  trigger:
  - platform: webhook
    webhook_id: motion_camera_bureau
  condition: []
  action:
  - data:
      message: Mouvement dans le bureau
    service: notify.telegram
  - data:
      camera_name: bureau
    service: shell_command.send_camera_snapshots
- id: '1595553550823'
  alias: Auto clim on
  description: ''
  trigger:
  - at: '10:00'
    platform: time
  condition: []
  action:
  - data:
      hvac_mode: cool
    entity_id: climate.climatisation
    service: climate.set_hvac_mode
- id: '1595553707817'
  alias: Auto clim off
  description: ''
  trigger:
  - at: '11:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: climate.climatisation
    service: climate.turn_off
- id: '1595598768398'
  alias: '[Simulation presence] Light off'
  description: ''
  trigger:
  - at: '21:30'
    platform: time
  condition: []
  action:
  - scene: scene.tout_eteindre
  mode: single
- id: '1595598882905'
  alias: '[Simulation presence] Light on'
  description: ''
  trigger:
  - at: '18:30'
    platform: time
  condition: []
  action:
  - brightness_pct: 100
    device_id: 486d6ad978584ce39674ee4760664c91
    domain: light
    entity_id: light.lampadaire_ikea
    type: turn_on
  - brightness_pct: 100
    device_id: ee405e7ef6d94b349f70029b47aea7d9
    domain: light
    entity_id: light.lampe_bureau
    type: turn_on
  mode: single
- id: '1601670145906'
  alias: Ventilation salle de bain
  description: ''
  trigger:
  - above: '70'
    entity_id: sensor.capteur_temp_sdb_humidity
    platform: numeric_state
  condition:
  - condition: and
    conditions:
    - before: '22:00'
      condition: time
      after: '6:00'
    - condition: state
      entity_id: switch.ventilation_salle_de_bain
      state: 'off'
  action:
  - data: {}
    entity_id: switch.ventilation_salle_de_bain
    service: switch.turn_on
  mode: single
- id: '1603999289566'
  alias: '[Alarme] Fenetre chambre ouverte'
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 6cc1928e9ce04a3f93c49ec220d85ff7
    entity_id: binary_sensor.fenetre_chambre_contact
    domain: binary_sensor
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.alarme
      state: armed_away
    - condition: state
      entity_id: alarm_control_panel.alarme
      state: armed_night
  action:
  - data:
      message: Fenêtre chambre ouverte
    service: notify.telegram
  mode: single
- id: '1608654081007'
  alias: '[Alarme] Mouvement sejour'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.camera_sejour_person
    from: 'off'
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.alarme
      state: armed_away
    - condition: state
      entity_id: alarm_control_panel.alarme
      state: armed_night
  action:
  - service: notify.telegram
    data:
      message: Mouvement dans le séjour
  - service: shell_command.send_snapshot_from_pi
    data:
      camera_name: sejour
  mode: single
- id: '1608655223529'
  alias: '[Alarme] Mouvement balcon'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.camera_balcon_person
    from: 'off'
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.alarme
      state: armed_away
    - condition: state
      entity_id: alarm_control_panel.alarme
      state: armed_night
  action:
  - service: notify.telegram
    data:
      message: Mouvement sur le balcon
  - service: shell_command.send_snapshot_from_pi
    data:
      camera_name: balcon
  mode: single
