- platform: ping
  name: MBP William Network
  host: 192.168.2.102
  count: 2
  scan_interval: 30

- platform: command_line
  name: MBP William Status
  device_class: lock
  command: ssh mbpwill 'sh .homeassistant/status.sh'
  scan_interval: 30
  payload_on: 'Unlocked'
  payload_off: 'Locked'
