- platform: ping
  name: mbp_william_network
  host: 192.168.2.102
  count: 2
  scan_interval: 30

- platform: command_line
  name: mbp_william_status
  device_class: lock
  command: ssh mbpwill 'sh .homeassistant/status.sh'
  scan_interval: 30
  payload_on: 'Unlocked'
  payload_off: 'Locked'

- platform: command_line
  name: camera_sejour_motion_sensor
  device_class: motion
  command: "python3 /home/homeassistant/.homeassistant/python_scripts/send_camera_command.py sejour getMotionAlert"
  value_template: '{{ value == "2" }}'
  scan_interval: 2

- platform: hikvision
  host: !secret camera_balcon_ip
  username: !secret camera_balcon_user
  password: !secret camera_balcon_password

- platform: mqtt
  name: camera_balcon_person
  state_topic: "frigate/camera_balcon/person"
  device_class: motion
  availability_topic: "frigate/available"

- platform: mqtt
  name: camera_sejour_person
  state_topic: "frigate/camera_sejour/person"
  device_class: motion
  availability_topic: "frigate/available"
