- platform: foscam
  name: camera_sejour
  ip: 192.168.2.118
  port: 88
  username: !secret camera_sejour_user
  password: !secret camera_sejour_password

- platform: generic
  name: camera_balcon
  still_image_url: !secret camera_balcon_still_image
  stream_source: !secret camera_balcon_stream_source
  username: !secret camera_balcon_user
  password: !secret camera_balcon_password
  authentication: digest

- platform: generic
  name: camera_bureau
  still_image_url: !secret camera_bureau_still_image
  stream_source: !secret camera_bureau_stream_source
