
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Home assistant
homeassistant:
  customize: !include customize.yaml

browser_mod:
  devices:
    75f96d16-9ecb59ca:
      name: mbp_will_chrome

panel_custom:
  - name: react-panel
    sidebar_title: React Demo
    sidebar_icon: mdi:react
    trust_external_script: true
    url_path: react-panel-demo
    js_url: http://192.168.2.102:8080/main.js
    embed_iframe: true
    # This will be available as prop `panel.config`.
    config:
      name: World

lovelace:
  mode: yaml
  dashboards:
    ui-experimental:
      title: Experimental
      filename: ui-experimental.yaml
      mode: yaml

# Themes
frontend:
  themes: !include_dir_merge_named themes

climate:
  platform: mqtt
  name: Climatisation
  initial: 22
  precision: 1.0
  min_temp: 18
  max_temp: 30
  fan_mode_command_topic: fujiac/fan/set
  fan_mode_state_topic: fujiac/state/get
  fan_mode_state_template: "{{ value_json.fan_mode }}"
  mode_command_topic: fujiac/mode/set
  mode_state_topic: fujiac/state/get
  mode_state_template: "{{ value_json.mode }}"
  swing_mode_command_topic: fujiac/swing/set
  swing_mode_state_topic: fujiac/state/get
  swing_mode_state_template: "{{ value_json.swing }}"
  temperature_command_topic: fujiac/temperature/set
  temperature_state_topic: fujiac/state/get
  temperature_state_template: "{{ value_json.temperature }}"
  current_temperature_topic: fujiac/state/get
  current_temperature_template: "{{ value_json.temperature }}"
  modes:
    - "auto"
    - "off"
    - "cool"
    - "dry"
    - "fan_only"
  fan_modes:
    - "auto"
    - "high"
    - "medium"
    - "low"
    - "quiet"
  swing_modes:
    - "on"
    - "off"

# Alarm
alarm_control_panel:
  - platform: manual
    name: Alarme
    disarmed:
      trigger_time: 0
      delay_time: 0
    armed_away:
      arming_time: 0
      delay_time: 0
    armed_night:
      arming_time: 0
      delay_time: 0

# Scripts
shell_command:
  send_camera_snapshots: python3 /home/homeassistant/.homeassistant/python_scripts/send_camera_snapshots.py {{camera_name}}
  send_camera_snapshot: python3 /home/homeassistant/.homeassistant/python_scripts/send_camera_snapshot.py {{camera_name}}
  send_sleep_command_mac: python3 /home/homeassistant/.homeassistant/python_scripts/send_sleep_command_mac.py

# Withings
withings:
  client_id: !secret withings_client_id
  client_secret: !secret withings_client_secret
  profiles:
    - William Mura

# Telegram Settings
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

# Notification services
notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id

# MQTT
mqtt:
  broker: localhost
  discovery: true
  discovery_prefix: homeassistant

automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
camera: !include camera.yaml
group: !include groups.yaml
history: !include history.yaml
homekit: !include homekit.yaml
input_boolean: !include input_boolean.yaml
logbook: !include logbook.yaml
recorder: !include recorder.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
