
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Home assistant
homeassistant:
  customize: !include customize.yaml

# Themes
frontend:
  themes: !include_dir_merge_named themes

# Alarm
alarm_control_panel:
  - platform: manual
    name: Alarme
    disarmed:
      trigger_time: 0
      delay_time: 0
    armed_away:
      pending_time: 0
      delay_time: 0
    armed_night:
      pending_time: 0
      delay_time: 0

# Scripts
shell_command:
  send_camera_snapshots: python3 /home/homeassistant/.homeassistant/python_scripts/send_camera_snapshots.py {{camera_name}}
  send_camera_snapshot: python3 /home/homeassistant/.homeassistant/python_scripts/send_camera_snapshot.py {{camera_name}}
  send_sleep_command_mac: python3 /home/homeassistant/.homeassistant/python_scripts/send_sleep_command_mac.py

# Withings
withings:
  client_id: !secret withings_client_id
  client_secret: !secret withings_client_secret
  profiles:
    - William Mura

# Telegram Settings
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

# Notification services
notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id

# MQTT
mqtt:
  broker: localhost
  discovery: true
  discovery_prefix: homeassistant

automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
camera: !include camera.yaml
group: !include groups.yaml
history: !include history.yaml
homekit: !include homekit.yaml
input_boolean: !include input_boolean.yaml
logbook: !include logbook.yaml
recorder: !include recorder.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
